name: Terraform Workflow

on:
  push:
    branches:
      - main  # o la rama que uses

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init
      working-directory: terraform_analisis

    - name: Terraform Plan
      run: terraform plan
      working-directory: terraform_analisis