name: Build Marp and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate MARP Presentation

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli

      - name: Generate HTML from Marp Markdown
        run: marp presentacion.md --html -o output/index.html

      - name: Copy media files
        run: cp -r Documentos/media output/media

      - name: Upload Presentation Artifact
        uses: actions/upload-artifact@v4
        with:
          name: marp-presentation
          path: output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: marp-presentation
          path: ./public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Print GitHub Pages URL
        run: 'echo "✅ La presentación está publicada en: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"'